### ISSUE TITLE
Not maintained anymore?

### ISSUE THREAD

**Issue by Dushistov** [brendanzab/approx#25]
Is crate still maintained?

**Comment by sebcrozet** [comment]
Ping @brendanzab . If you are not maintaining this crate any more, I can volunteer to help if you want!

**Comment by brendanzab** [comment]
Still maintained! Just hadn't needed updates! But it seems I do now. I can add @sebcrozet as a collaborator and crate owner too.

**Comment by brendanzab** [comment]
YEEEEKS! No wonder I haven't been seeing updates - I wasn't supcribed to the repo for some reason. Thanks a bunch for the ping!

**Comment by brendanzab** [comment]
@sebcrozet you should see an invite to manage approx as an owner on crates.io now!

**Comment by sebcrozet** [comment]
Thanks @brendanzab !

**Comment by brendanzab** [comment]
Just published 0.2!
