### ISSUE TITLE
V0.2 ist incompatible with nalgebra

### ISSUE THREAD

**Issue by fabric-and-ink** [brendanzab/approx#36]
Version 0.2 of approx is not compatible with nalgebra anymore:

```
130 |         relative_eq!(self.pos, other.pos)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `approx::RelativeEq` is not implemented for `nalgebra::Point<f32, nalgebra::U3>`
```

**Comment by sebcrozet** [comment]
I'm closing this since the problem here is because of nalgebra so this issue should be opened on the nalgebra [repository](https://github.com/sebcrozet/nalgebra). nalgebra currently depends on approx 0.1. and will be updated to the version 0.2 of approx as soon as mul-complex 0.2 is released.
