### ISSUE TITLE
Use macro on Rust 1.30

### ISSUE THREAD

**Issue by nilgoyette** [brendanzab/approx#42]
I replaced all `#[macro_use] extern crate approx;` in my project with simple `use`.

It went well for `relative_eq!`, but not for `assert_relative_eq!`. When I try to use it, the compiler tells me that `__assert_approx` is missing, then  `relative_eq` is missing, so I need to type:

    use approx::{assert_relative_eq, __assert_approx, relative_eq};

I know I can a) keep `#[macro_use]` or b) `use approx::*;` but neither are interesting.

**Comment by brendanzab** [comment]
iiinteresting! We'll have to figure out what is up with this. 🤔

**Comment by brendanzab** [comment]
0.3.1 is now published
