### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by benluelo** [brendanzab/approx#75]
This crate is very widely used; is there any report on it's maintenance status? There are several good PRs open to remove unsafe and fix some clippy warnings; I think it would be a good idea to review and merge those in and release a new version. (This library came up while using cargo-geiger on several different libraries.)

**Comment by sebcrozet** [comment]
Thank you for opening this issue! I’m not the original maintainer of this crate, but I do have the necessary accesses to perform maintenance work on it. I merged a few PR that seemed to the the most important for now.

**Comment by benluelo** [comment]
Awesome, thank you! Any idea if/ when a new version will be released on crates.io?

**Comment by sebcrozet** [comment]
The new version has been published.
