### ISSUE TITLE
Absolute tolerance

### ISSUE THREAD

**Issue by Andlon** [brendanzab/approx#8]
I find this library really useful, however sometimes you actually _want_ to compare two numbers using their absolute difference. Could it perhaps be desirable to have an additional macro for this purpose? I find this perhaps particularly useful when comparing with zero.

``` rust
// The name is perhaps not perfect
assert_absdiff_eq!(x, y, tol = 1e-8);

// I actually suggest not providing a default tolerance, as I believe
// absolute difference should only be used when you already have
// a specific tolerance in mind
```

I could certainly try to make a PR for this, but I thought I'd see if there's interest in it first.

**Comment by brendanzab** [comment]
Hmm, I would like to understand the use cases more. Maybe having some examples would help? Could we potentially have another function on the trait for this?

**Comment by brendanzab** [comment]
Sorry for the super delayed reply too! 😰

**Comment by Andlon** [comment]
Sure! ULP-based comparison is useful if you know that two floating point numbers are supposed to be almost identical. However, for more involved algorithms the numerical drift from roundoff errors becomes significant, and you usually don't have any idea about how many ULPs you need to use for your tolerance.

I do a lot of numerical analysis. In these cases, you often have an error bound expressed in terms of absolute difference. For example, the (backward) error for a standard dot product of vectors `x` and `y` is

```
| fl(dot(x, y)) - dot(x, y) | <= c * n * eps * dot(|x|, |y|)
```

where `n` is the length of the vectors `x` and `y`, `c` is a constant of order unity (i.e. close to `1`), `eps` is the machine epsilon and `|x|` denotes a vector whose elements are absolute values of those in `x`.

This isn't actually a practical error bound because you don't possess the exact solution for `dot(|x|, |y|)` - I just grabbed a result from a nearby book. In any case, my point is that error bounds are almost always specified in terms of some kind of absolute value difference (or more generally differences in norms).

Moreover, the relative/ULP-based comparison is far superior when comparing arbitrary numbers (as seen in e.g. the randomascii blog post), but if you know the quantities of the numbers you are comparing, it's often far easier (and equally correct) to judiciously choose an absolute value difference.

Computing absolute difference is pretty trivial, of course:

```
let a = 3.6;
let b = 3.7;
assert!((a - b).abs() <= 0.2);
```

but compare the last line to:

```
// Again, not so sure about name
assert_absdiff_eq!(x, y, tol = 0.2)
```

One additional benefit here is that the macro can also display an error message with the actual error involved if the assertion fails. The first homegrown example is super annoying to debug, because it doesn't tell you the size of the numbers, so you have to hook up a debugger or add print statements. We use this to provide [useful assertions on matrices in rulinalg](https://docs.rs/rulinalg/0.4.2/rulinalg/macro.assert_matrix_eq.html).

My original issue is perhaps confusing because I said " I find this perhaps particularly useful when comparing with zero." According to the aforementioned randomascii blog post, comparing with zero is usually the very reason one should not use absolute differences! I don't remember what I meant here, but I can imagine I had in mind knowing the quantities of the numbers involved, in which case comparing with zero using absolute differences can be justified.

**Comment by brendanzab** [comment]
I'm wondering if having a base trait would be useful. Could then implement it for signed and unsigned integers too, which could address @sebcrozet's [comment](https://github.com/brendanzab/approx/issues/6#issuecomment-246201218) on #6:

```rust
pub trait AbsDiffEq {
    type Tolerance;

    fn abs_diff_eq(&self, other: &Self, tolerance: Self::Tolerance) -> bool;

    fn abs_diff_ne(&self, other: &Self, tolerance: Self::Tolerance) -> bool {
        !Self::abs_diff_eq(self, other, tolerance)
    }
}
```

Would you prefer it be called 'tolerance' over 'epsilon'?

**Comment by Andlon** [comment]
Well, `epsilon` can perhaps easily be mistaken for machine epsilon, which is why I personally prefer `tolerance`.

As for supporting absolute difference comparison of integers, we do this in rulinalg, but this has the unfortunate effect of not allowing us to use e.g. `LowerExp` for scientific notation when displaying error messages, since it's not implemented for integers (I guess this is the real problem - why is it not?). I can imagine that the use cases for approximate comparison of integers are almost non-existent though.

**Comment by brendanzab** [comment]
@Andlon I've started a new issue regarding naming!
