### ISSUE TITLE
Implement ApproxEq for num::Complex

### ISSUE THREAD

**Issue by sebcrozet** [brendanzab/approx#9]
While this adds a dependency to `num-complex`, this would be very useful. I can prepare a PR if it would be accepted.

**Comment by SuperFluffy** [comment]
I think this might be useful. If you make this into an optional feature, users can explicitly opt into `num-complex`.

I guess you intend to implement this by comparing two floating point numbers with the same accuracy?

**Comment by brendanzab** [comment]
This would be useful, but I think I would rather the dependency go the other way. This would probably require stabilising approx though, and making the case for its inclusion in that library. Do we know who the principle maintainer is?

**Comment by brendanzab** [comment]
Perhaps we could make the case for adding an `approx` feature to the [Cargo.toml](https://github.com/rust-num/num/blob/e2ea246016b47f3f54f46b685619e725c150a841/complex/Cargo.toml)?

**Comment by cuviper** [comment]
Given the wide use of num, I am very conservative with changes, and hesitant to add external dependencies to the public API.  I already have the issue that its optional serde dependency is behind the times, with no clear path for bumping to serde-1.0 without a breaking change.  So if we added approx at all, I'd want to wait for approx-1.0 and might never bump from there.

(Inter-crate semver is hard... I feel this is something the Rust ecosystem is still figuring out.)
